<?php

namespace AppBundle\Repository;

/**
 * ProjectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReservaRepository extends \Doctrine\ORM\EntityRepository
{

    public function findAllReservasByHotel($id)
    {
        $query = $this->createQueryBuilder("reserva")
            ->join('reserva.habitacion', 'habitacion')
            ->join('habitacion.hotel', 'hotel')
            ->select('reserva.fecha','reserva.id','reserva.estado',
                            'reserva.entrada','reserva.salida',
                            'reserva.codigo','habitacion.precio')
            ->where('hotel.id = :id')
            ->setParameter('id', $id);

        return $query
            ->getQuery()
            ->getResult();
    }
}
