<?php

namespace AppBundle\Repository;

/**
 * ProjectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReservaRepository extends \Doctrine\ORM\EntityRepository
{

    public function findOneReservaByCodeHotelPin($codeR, $pinH)
    {
        $query = $this->createQueryBuilder("reserva")
            ->join('reserva.habitacion', 'habitacion')
            ->join('habitacion.hotel', 'hotel')
            ->select('reserva')
            ->where('reserva.codigo = :code and hotel.pin = :pin')
            ->setParameter('code', $codeR)
            ->setParameter('pin', $pinH);

        return $query
            ->getQuery()
            ->getResult();
    }


    public function findAllReservasByHotel($id)
    {
        $query = $this->createQueryBuilder("reserva")
            ->join('reserva.habitacion', 'habitacion')
            ->join('habitacion.hotel', 'hotel')
            ->select('reserva.fecha', 'reserva.id', 'reserva.estado',
                'reserva.entrada', 'reserva.salida',
                'reserva.codigo', 'habitacion.precio')
            ->where('hotel.id = :id and reserva.estado = 1')
            ->setParameter('id', $id);

        return $query
            ->getQuery()
            ->getResult();
    }
}
